[package]
name = "fast-paillier"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Optimized Paillier encryption scheme"
repository = "https://github.com/LFDT-Lockness/fast-paillier"
categories = ["algorithms", "cryptography"]
keywords = ["paillier", "public-key", "encryption"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Deps for rug
rug = { version = "1.24", optional = true, default-features = false, features = ["std", "integer", "rand"] }
bytemuck = { version = "1.5", features = ["derive"], optional = true }
# Deps for num-bigint
num-bigint = { version = "0.4.6", optional = true, default-features = false, features = ["std", "rand"] }
num-traits = { version = "0.2.19", optional = true }
num-integer = { version = "0.1.46", optional = true }
glass_pumpkin = { version = "1.7", optional = true }
rand = { version = "0.8", optional = true, default-features = false }

rand_core = "0.6"

thiserror = "1"

serde = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
rand_dev = "0.1"
rand = { version = "0.8", default-features = false }

# Used to test serialization when serde is enabled
rug = { version = "1.24", default-features = false, features = ["std", "integer", "rand", "serde"] }
serde_json = "1"
ciborium = "0.2.2"

# Used for benchmarks
criterion = { version = "0.5", features = ["html_reports"] }
libpaillier = { version = "0.5", default-features = false, features = ["gmp"] }

[features]
default = ["backend-num-bigint"]

serde = ["dep:serde"]
backend-rug = ["dep:rug", "dep:bytemuck"]
backend-num-bigint = ["dep:num-bigint", "dep:num-traits", "dep:num-integer", "dep:glass_pumpkin", "dep:rand"]

[[bench]]
name = "comparison"
harness = false

# Make the backend less slow in debug builds to speed up tests
[profile.dev.package]
num-bigint.opt-level = 3
num-traits.opt-level = 3
num-integer.opt-level = 3
glass_pumpkin.opt-level = 3
