name: Rust

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUSTFLAGS: --deny warnings

jobs:
  build-and-test-num-bigint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: |
        cargo build --features serde
        cargo bench --no-run --features serde
    - name: Run tests
      run: cargo test --features serde
  build-and-test-rug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: |
        cargo build --no-default-features --features serde,backend-rug
        cargo bench --no-run --no-default-features --features serde,backend-rug
    - name: Run tests
      run: cargo test --no-default-features --features serde,backend-rug

  build-with-different-feature-sets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Build
      run: |
        cargo build --no-default-features --features backend-rug,std
        cargo build --no-default-features --features backend-num-bigint,std
        cargo build --no-default-features --features backend-num-bigint,no_std
        cargo build --all-features

  build-wasm-nostd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Install wasm32-unknown-unknown toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: >
        cargo check -p fast-paillier
          --no-default-features
          --features backend-num-bigint,no_std,serde
          --target wasm32-unknown-unknown

  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --all -- --check
  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Run clippy
      run: "cargo clippy --all --all-features --lib -- -D clippy::all"
    - name: Run clippy tests
      run: "cargo clippy --tests --benches --all-features -- -D clippy::all"
  check-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check changelogs
      run: ./.github/changelog.sh
